from . import customer_rental_return_wizard
from . import purchase_order
from . import rental_contract
from . import res_users
from . import sale_order
from . import separate_picking
from . import stock_inventory
from . import stock_report_quantity_by_location_prepare
from . import stock_scrap
from . import ywt_internal_stock_transfer
