from . import account_move
from . import cut_wizard
from . import hr_contract
from . import hr_leave
from . import hr_leave_completion
from . import hr_leave_cut
from . import hr_leave_type
from . import register_payment
from . import res_config_settings
from . import account_bank_statement_line
from . import account_payment
