from . import account_analytic_plan
from . import hr_contract
from . import hr_employee
from . import hr_eos_resignation
from . import hr_leave
from . import hr_leave_type
from . import hr_payroll_structure
from . import hr_payslip
from . import hr_resignation
from . import hr_resignation_reason
from . import hr_resignation_reason_rule
