from . import account_move
from . import add_deduct_wizard
from . import add_fine_wizard
from . import confirmation_wizard
from . import customer_rental_fine_wizard
from . import customer_rental_plan
from . import customer_rental_policy
from . import customer_rental_pricing
from . import customer_rental_pricing_lines
from . import customer_rental_return_wizard
from . import customer_rental_setting
from . import delay_due_amount_lines
from . import extend_contract_payment_wizard
from . import extend_wizard
from . import fleet_vehicle
from . import product_template
from . import rental_additional_service
from . import rental_contract
from . import rental_contract_lines
from . import res_partner
from . import res_users
from . import stock_location
from . import account_bank_statement_line
from . import account_payment
from . import product_product
