from . import account_journal
from . import authorization_country
from . import close_naql_contract
from . import customer_rental_policy
from . import extend_wizard
from . import extended_coverage
from . import get_data
from . import inspection_wizard
from . import naql_contract_logs
from . import naql_create_contract
from . import naql_lookups
from . import naql_main_close_code
from . import naql_sub_close_code
from . import naql_suspend_code
from . import otp_confirm
from . import rental_contract
from . import rental_policy
from . import res_company
from . import res_config_settings
from . import res_country
from . import stock_location
from . import suspend_naql_contract
from . import vehicle_naql_contract_wizard
from . import view_naql_contract_wizard
