from . import fleet_vehicle
from . import fleet_vehicle_model
from . import fleet_vehicle_model_brand
from . import fleet_vehicle_model_category
from . import product_category
from . import product_product
from . import product_template
from . import stock_move
from . import stock_picking
from . import usage_type
