from . import allowed_attendance_location
from . import hr_attendance
from . import hr_employee
from . import hr_employee_base
from . import hr_leave
from . import hr_payslip
from . import hr_public_holiday
from . import mobile_terms_policy
from . import notification_log
from . import res_config_settings
from . import hr_employee_public
