from . import account_asset
from . import account_move
from . import account_move_line
from . import account_payment
from . import account_tax
from . import bill_information_wizard
from . import create_vehicle_wizard
from . import export_vehicle_excel
from . import fleet_vehicle
from . import installment_line
from . import leasing_payment
from . import product_template
from . import purchase_data
from . import purchase_order
from . import purchase_order_line
from . import purchase_type
from . import vehicle_data
from . import account_bank_statement_line
from . import product_product
