from . import action_closed
from . import add_product
from . import deviation_limit
from . import fleet_vehicle
from . import res_config_settings
from . import stock_location
from . import stock_move
from . import stock_picking
from . import stock_quant
from . import vehicle_checklist
from . import vehicle_driver
from . import ywt_internal_stock_transfer
from . import ywt_internal_stock_transfer_line
