from . import accident_discount_wizard
from . import accident_follower_wizard
from . import account_move
from . import evaluation_party
from . import fleet_vehicle
from . import insurance_policy_line
from . import not_insurance_reason
from . import rental_contract
from . import res_company
from . import res_config_settings
from . import vehicle_accident
from . import vehicle_accident_lines
from . import account_bank_statement_line
from . import account_payment
