from . import account_asset
from . import account_move
from . import account_move_line
from . import fleet_vehicle
from . import insurance_policy
from . import insurance_policy_line
from . import po_insurance_line
from . import purchase_order
from . import purchase_order_line
from . import res_config_settings
from . import account_bank_statement_line
from . import account_payment
