from . import add_statement_wizard
from . import cancel_arrest_warrant
from . import cancel_arrest_warrant_wizard
from . import fleet_vehicle
from . import generalization
from . import generalization_wizard
from . import rental_contract
from . import res_users
from . import statement
