from . import account_move
from . import fleet_vehicle
from . import maintenance_repair_task_line
from . import maintenance_request
from . import maintenance_spare_part_line
from . import maintenance_stage
from . import maintenance_team
from . import maintenance_workshop
from . import preventive_maintenance_plan
from . import product_template
from . import repair_task
from . import res_company
from . import res_config_settings
from . import res_users
from . import stock_picking
from . import transfer_stock_line
from . import vehicle_preventive_maintenance
from . import account_bank_statement_line
from . import account_payment
from . import product_product
